backend:
  name: github
  repo: goodxgrief/studentenfutter  # GitHub-Repo
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Seiten"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }